<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>masm</string>
	</array>
	<key>name</key>
	<string>MASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(r0|r1|r2|r3|r4|r5|r6|r7|r8|r9|r10|r11|r12|r13|r14|r15|ra|rb|rc|rd|re|rf|sp|aux)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\S+)\s*:</string>
			<key>name</key>
			<string>entity.name.section.label</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\'.\'|\'\\.\'</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;.*)$</string>
			<key>name</key>
			<string>comment.line.character</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.dec</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\+|-)?\d+</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9a-fA-F]+x)\W</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.oct</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-7]+o)\W</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.bin</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-1]+b)\W</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:jif\(.*\)|noop|jn|j|je|jne|jl|jg|jle|jge|jz|jnz|jp|jpz|jm|jmz|load|store|cmp|in|halt|inbutton|insw|inchar|inmen|sleep|out|outled|outseg1|outseg2|outpx|outmem|move|set|addi|subi|add|sub|mul|div|shift\(.*\)|shiftl0|shiftr0|shiftl1|shiftr1|rotl|rotr|and|or|xor|not)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:push|pop|mod)\b</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.masm</string>
</dict>
</plist>
